name: Update RSS Feed

on:
  schedule:
    - cron: '0 */3 * * *'  # каждые 3 часа
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run RSS parser
        run: |
          echo "=== Запускаю скрипт ==="
          python rss_parser.py
          echo "=== Скрипт завершён ==="
          ls -la

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rss.xml || echo "Файл не найден, нечего коммитить"
          git commit -m "Update RSS feed" || echo "Нет изменений для коммита"
          git push || echo "Нечего пушить"
