name: Update RSS Feed

on:
  schedule:
    - cron: "0 */3 * * *"  # каждые 3 часа
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requirements (if any)
        run: pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run RSS parser
        run: |
          echo "=== Запускаю скрипт ==="
          python rss_parser.py
          echo "=== Скрипт завершён ==="
          ls -la

      - name: Commit and push updated RSS
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git status
          git add rss.xml || echo "Нечего добавлять"
          git status
          git commit -m "Update RSS feed" || echo "Нечего коммитить"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push не удался"
